export interface Prompt {
  id: number;
  category: string;
  text: string;
  descriptionKo: string;
}

export const prompts: Prompt[] = [
    // 1-20 Boy Group (Idol)
    { id: 1, category: 'BoyGroup', text: 'Male Group, Powerful high notes, Synchronized chorus, Dark concept', descriptionKo: '남성 그룹, 파워풀한 고음, 칼군무 코러스, 다크 컨셉' },
    { id: 2, category: 'BoyGroup', text: 'Male, Refreshing energy, Bright, Summer vibe, High teen', descriptionKo: '남성, 청량한 에너지, 밝은, 썸머 바이브, 하이틴 스타일' },
    { id: 3, category: 'BoyGroup', text: 'Male Rapper, Deep voice, Aggressive flow, Trap beat', descriptionKo: '남성 래퍼, 굵은 동굴 목소리, 공격적인 플로우, 트랩 비트' },
    { id: 4, category: 'BoyGroup', text: 'Male Vocal Line, R&B style ad-libs, Emotional, Harmonies', descriptionKo: '남성 보컬 라인, R&B 스타일 애드리브, 감성적인, 풍성한 화음' },
    { id: 5, category: 'BoyGroup', text: 'Male, Whisper rap intro, Sexy concept, Heavy bass', descriptionKo: '남성, 속삭이는 랩 도입부, 섹시 컨셉, 묵직한 베이스' },
    { id: 6, category: 'BoyGroup', text: 'Male, Auto-tuned hook, Future bass, Cyberpunk style', descriptionKo: '남성, 오토튠 훅, 퓨처 베이스, 사이버펑크 스타일' },
    { id: 7, category: 'BoyGroup', text: 'Male, Rock-tinged vocals, Electric guitar, Anime OST vibe', descriptionKo: '남성, 락 스타일 보컬, 일렉 기타, 애니메이션 OST 느낌' },
    { id: 8, category: 'BoyGroup', text: 'Male, Groovy, Funk bass, Retro disco, Falsetto chorus', descriptionKo: '남성, 그루비한, 펑크 베이스, 레트로 디스코, 가성 코러스' },
    { id: 9, category: 'BoyGroup', text: 'Male Group, Chant-style chorus, Anthem, Stadium cheering', descriptionKo: '남성 그룹, 구호(Chant) 스타일 코러스, 앤섬, 스타디움 함성' },
    { id: 10, category: 'BoyGroup', text: 'Male, Mumble rap verse, Melodic pre-chorus, Hip-hop', descriptionKo: '남성, 멈블 랩 벌스, 멜로디컬한 프리코러스, 힙합' },
    { id: 11, category: 'BoyGroup', text: 'Male, Sweet boyfriend tone, Acoustic guitar, Fan song', descriptionKo: '남성, 달콤한 남친 톤, 어쿠스틱 기타, 팬송' },
    { id: 12, category: 'BoyGroup', text: 'Male, Growling rap, Intense dance break, EDM drop', descriptionKo: '남성, 으르렁거리는 랩, 강렬한 댄스 브레이크, EDM 드롭' },
    { id: 13, category: 'BoyGroup', text: 'Male, Dreamy synth-pop, Ethereal vocals, Sophisticated', descriptionKo: '남성, 몽환적인 신스팝, 신비로운 보컬, 세련된 느낌' },
    { id: 14, category: 'BoyGroup', text: 'Male, Latin pop rhythm, Reggaeton beat, Passionate', descriptionKo: '남성, 라틴 팝 리듬, 레게톤 비트, 열정적인' },
    { id: 15, category: 'BoyGroup', text: 'Male, 90s Hip-hop vibe, Old school scratch, Boom Bap', descriptionKo: '남성, 90년대 힙합 감성, 올드스쿨 스크래치, 붐뱁' },
    { id: 16, category: 'BoyGroup', text: 'Male, Clear tenor, High piercing note, Bridge climax', descriptionKo: '남성, 맑은 테너, 찌르는 듯한 고음, 브릿지 클라이막스' },
    { id: 17, category: 'BoyGroup', text: 'Male, Playful, Witty lyrics, Bright brass, Carnival', descriptionKo: '남성, 장난기 넘치는, 재치 있는 가사, 밝은 브라스, 카니발' },
    { id: 18, category: 'BoyGroup', text: 'Male, Sad melody, Orchestral strings, Emotional ballad', descriptionKo: '남성, 슬픈 멜로디, 오케스트라 스트링, 감성 발라드' },
    { id: 19, category: 'BoyGroup', text: 'Male, Fast rapping, Diction heavy, Speed rap', descriptionKo: '남성, 속사포 랩, 딕션이 강조된, 스피드 랩' },
    { id: 20, category: 'BoyGroup', text: 'Male, Sexy breathing, R&B slow jam, Body wave', descriptionKo: '남성, 섹시한 숨소리, R&B 슬로우 잼, 바디 웨이브' },

    // 21-40 Girl Group (Idol)
    { id: 21, category: 'GirlGroup', text: 'Female Group, High teen fresh, Cheerful, School uniform vibe', descriptionKo: '여성 그룹, 하이틴 프레시, 발랄한, 스쿨룩 감성' },
    { id: 22, category: 'GirlGroup', text: 'Female, Girl Crush, Heavy bass, Charismatic rap', descriptionKo: '여성, 걸크러쉬, 강한 베이스, 카리스마 랩' },
    { id: 23, category: 'GirlGroup', text: 'Female, Dreamy, Fairy tale concept, Synth-pop, Magical', descriptionKo: '여성, 몽환적인, 동화 컨셉, 신스팝, 마법 같은 분위기' },
    { id: 24, category: 'GirlGroup', text: 'Female, Retro city pop, Nostalgic, 80s synth', descriptionKo: '여성, 레트로 시티팝, 향수 어린, 80년대 신디사이저' },
    { id: 25, category: 'GirlGroup', text: 'Female, Powerful high notes, Diva vibe, Main vocal solo', descriptionKo: '여성, 파워풀한 고음, 디바 분위기, 메인보컬 솔로' },
    { id: 26, category: 'GirlGroup', text: 'Female, Cute & Bubbly, Catchy hook, TikTok challenge style', descriptionKo: '여성, 귀엽고 통통 튀는, 중독성 있는 훅, 틱톡 챌린지 스타일' },
    { id: 27, category: 'GirlGroup', text: 'Female, Elegant, Classical strings, Ballet core', descriptionKo: '여성, 우아한, 클래식 스트링, 발레코어' },
    { id: 28, category: 'GirlGroup', text: 'Female, Hip-hop swag, Trap beat, Confident lyrics', descriptionKo: '여성, 힙합 스웨그, 트랩 비트, 자신감 넘치는 가사' },
    { id: 29, category: 'GirlGroup', text: 'Female, Summer queen, Tropical house, Cool breeze', descriptionKo: '여성, 썸머 퀸, 트로피컬 하우스, 시원한 바람' },
    { id: 30, category: 'GirlGroup', text: 'Female, Mysterious, Minor key, Horror concept', descriptionKo: '여성, 미스터리한, 단조, 호러 컨셉' },
    { id: 31, category: 'GirlGroup', text: 'Female, UK Garage beat, Fast tempo, Trendy', descriptionKo: '여성, UK 개러지 비트, 빠른 템포, 트렌디한' },
    { id: 32, category: 'GirlGroup', text: 'Female, Minimalist beat, ASMR vocals, Whispering', descriptionKo: '여성, 미니멀한 비트, ASMR 보컬, 속삭이는' },
    { id: 33, category: 'GirlGroup', text: 'Female, Rock chick, Punk guitar, Rebel spirit', descriptionKo: '여성, 락 시크, 펑크 기타, 반항적인 정신' },
    { id: 34, category: 'GirlGroup', text: 'Female, R&B groove, Soulful ad-libs, Late night', descriptionKo: '여성, R&B 그루브, 소울풀한 애드리브, 늦은 밤' },
    { id: 35, category: 'GirlGroup', text: 'Female, EDM pop, Festival drop, Party energy', descriptionKo: '여성, EDM 팝, 페스티벌 드롭, 파티 에너지' },
    { id: 36, category: 'GirlGroup', text: 'Female, Moombahton rhythm, Exotic, Dance break', descriptionKo: '여성, 뭄바톤 리듬, 이국적인, 댄스 브레이크' },
    { id: 37, category: 'GirlGroup', text: 'Female, Acapella intro, Harmonious, Pure voices', descriptionKo: '여성, 아카펠라 도입부, 화음, 순수한 목소리' },
    { id: 38, category: 'GirlGroup', text: 'Female, Y2K aesthetic, Hip-hop pants, Old school vibe', descriptionKo: '여성, Y2K 감성, 힙합 바지, 올드스쿨 바이브' },
    { id: 39, category: 'GirlGroup', text: 'Female, Emotional ballad, Piano accompaniment, Tears', descriptionKo: '여성, 감성 발라드, 피아노 반주, 눈물' },
    { id: 40, category: 'GirlGroup', text: 'Female, Latin vibe, Guitar strumming, Seductive', descriptionKo: '여성, 라틴 바이브, 기타 스트러밍, 매혹적인' },

    // 41-60 Ballad & R&B
    { id: 41, category: 'Ballad', text: 'Male, Deep husky voice, Heartbreak, K-Drama OST', descriptionKo: '남성, 굵은 허스키 보이스, 이별, 한국 드라마 OST' },
    { id: 42, category: 'Ballad', text: 'Female, Crystal clear voice, High pitch, Snow theme', descriptionKo: '여성, 수정처럼 맑은 목소리, 고음, 눈(Snow) 테마' },
    { id: 43, category: 'Ballad', text: 'Male, Groovy R&B, Falsetto runs, Coffee shop vibe', descriptionKo: '남성, 그루비한 R&B, 가성 기교, 카페 분위기' },
    { id: 44, category: 'Ballad', text: 'Female, Jazzy piano, Soulful, Rainy day', descriptionKo: '여성, 재즈 피아노, 소울풀한, 비 오는 날' },
    { id: 45, category: 'Ballad', text: 'Duet, Male & Female, Harmony, Wedding song, Sweet', descriptionKo: '듀엣, 남녀, 화음, 결혼식 축가, 달콤한' },
    { id: 46, category: 'Ballad', text: 'Male, Rock Ballad, Screaming high note, Electric guitar solo', descriptionKo: '남성, 락 발라드, 샤우팅 고음, 일렉 기타 솔로' },
    { id: 47, category: 'Ballad', text: 'Female, Indie folk, Acoustic guitar, Calm, Healing', descriptionKo: '여성, 인디 포크, 통기타, 차분한, 힐링' },
    { id: 48, category: 'Ballad', text: 'Male, Orchestral epic, Grand build-up, Historical drama', descriptionKo: '남성, 웅장한 오케스트라, 거대한 빌드업, 사극 드라마' },
    { id: 49, category: 'Ballad', text: 'Female, Breathless tone, Sad ending, Piano only', descriptionKo: '여성, 숨소리 섞인 톤, 슬픈 엔딩, 피아노 독주' },
    { id: 50, category: 'Ballad', text: 'Male, Neo-soul, Complex chords, Stylish vocals', descriptionKo: '남성, 네오 소울, 복잡한 코드, 스타일리시한 보컬' },
    { id: 51, category: 'Ballad', text: 'Female, Power vocal, Belting, Audition program climax', descriptionKo: '여성, 파워 보컬, 벨팅 창법, 오디션 프로그램 클라이막스' },
    { id: 52, category: 'Ballad', text: 'Male, Soft whisper, Morning alarm, Gentle', descriptionKo: '남성, 부드러운 속삭임, 모닝 알람, 다정한' },
    { id: 53, category: 'Ballad', text: 'Female, R&B divas, Vocal runs, Melisma', descriptionKo: '여성, R&B 디바, 화려한 기교, 멜리스마' },
    { id: 54, category: 'Ballad', text: 'Male, Folk ballad, Harmonica, Nostalgia for home', descriptionKo: '남성, 포크 발라드, 하모니카, 고향에 대한 향수' },
    { id: 55, category: 'Ballad', text: 'Female, Modern rock ballad, Band sound, Emotional', descriptionKo: '여성, 모던 락 발라드, 밴드 사운드, 감성적인' },
    { id: 56, category: 'Ballad', text: 'Male, City R&B, Driving at night, Sophisticated beat', descriptionKo: '남성, 시티 R&B, 밤 운전, 세련된 비트' },
    { id: 57, category: 'Ballad', text: 'Female, Disney style, Musical theater, Hopeful', descriptionKo: '여성, 디즈니 스타일, 뮤지컬, 희망찬' },
    { id: 58, category: 'Ballad', text: 'Male, Sorrowful, Traditional Korean sentiment (Han)', descriptionKo: '남성, 애절한, 한국적 정서(한)' },
    { id: 59, category: 'Ballad', text: 'Female, Bossa Nova style, Relaxed, Brunch vibe', descriptionKo: '여성, 보사노바 스타일, 편안한, 브런치 분위기' },
    { id: 60, category: 'Ballad', text: 'Choir, Gospel influence, Grand finale, Uplifting', descriptionKo: '합창단, 가스펠 영향, 그랜드 피날레, 벅차오르는' },

    // 61-80 Hip-Hop & Dance
    { id: 61, category: 'HipHop', text: 'Male, Hard Trap, 808 Bass, Diss track vibe', descriptionKo: '남성, 하드 트랩, 808 베이스, 디스곡 분위기' },
    { id: 62, category: 'HipHop', text: 'Female, Singing Rap, Melodic, Trendy pop rap', descriptionKo: '여성, 싱잉 랩, 멜로디컬한, 트렌디 팝 랩' },
    { id: 63, category: 'HipHop', text: 'Male, Old School Boom Bap, Jazzy sample, Laid back', descriptionKo: '남성, 올드스쿨 붐뱁, 재즈 샘플링, 여유로운' },
    { id: 64, category: 'HipHop', text: 'Female, Jersey Club beat, Fast, Dance challenge', descriptionKo: '여성, 저지 클럽 비트, 빠른, 댄스 챌린지' },
    { id: 65, category: 'HipHop', text: 'Male, Drill beat, Dark, Grime influence', descriptionKo: '남성, 드릴 비트, 어두운, 그라임 영향' },
    { id: 66, category: 'HipHop', text: 'Female, House music, Vogue dance, Runway style', descriptionKo: '여성, 하우스 뮤직, 보깅 댄스, 런웨이 스타일' },
    { id: 67, category: 'HipHop', text: 'Male, EDM Big Room, Festival Drop, Jump', descriptionKo: '남성, EDM 빅룸, 페스티벌 드롭, 점프' },
    { id: 68, category: 'HipHop', text: 'Female, Disco Funk, Retro strings, Roller skate', descriptionKo: '여성, 디스코 펑크, 레트로 스트링, 롤러스케이트' },
    { id: 69, category: 'HipHop', text: 'Male, Autotune emo rap, Sad guitar, Melancholy', descriptionKo: '남성, 오토튠 이모 랩, 슬픈 기타, 우울한' },
    { id: 70, category: 'HipHop', text: 'Female, Twerk beat, Heavy bass, Bold', descriptionKo: '여성, 트월크 비트, 강한 베이스, 대담한' },
    { id: 71, category: 'HipHop', text: 'Male, G-Funk, West coast whistle, Summer drive', descriptionKo: '남성, 지펑크, 웨스트 코스트 휘파람, 여름 드라이브' },
    { id: 72, category: 'HipHop', text: 'Female, Glitch hop, Hyperpop, Experimental', descriptionKo: '여성, 글리치 합, 하이퍼팝, 실험적인' },
    { id: 73, category: 'HipHop', text: 'Male, Reggae fusion, Dancehall, Island vibe', descriptionKo: '남성, 레게 퓨전, 댄스홀, 아일랜드 바이브' },
    { id: 74, category: 'HipHop', text: 'Female, Tech House, Minimal, Club banger', descriptionKo: '여성, 테크 하우스, 미니멀, 클럽 뱅어' },
    { id: 75, category: 'HipHop', text: 'Male, Rock Rap, Nu-metal influence, Aggressive', descriptionKo: '남성, 락 랩, 뉴메탈 영향, 공격적인' },
    { id: 76, category: 'HipHop', text: 'Female, Latin Trap, Spanish guitar, Sensual', descriptionKo: '여성, 라틴 트랩, 스패니시 기타, 관능적인' },
    { id: 77, category: 'HipHop', text: 'Male, Jazz Hop, Piano loop, Studying vibe', descriptionKo: '남성, 재즈 합, 피아노 루프, 공부할 때 듣기 좋은' },
    { id: 78, category: 'HipHop', text: 'Female, Bubblegum Pop, High energy, Aerobics', descriptionKo: '여성, 버블검 팝, 높은 에너지, 에어로빅' },
    { id: 79, category: 'HipHop', text: 'Male, Phonk, Cowbell, Drift car video style', descriptionKo: '남성, 폰크, 카우벨, 드리프트 영상 스타일' },
    { id: 80, category: 'HipHop', text: 'Female, Dubstep break, Heavy drop, Performance', descriptionKo: '여성, 덥스텝 브레이크, 헤비 드롭, 퍼포먼스' },

    // 81-100 Special Concepts
    { id: 81, category: 'Special', text: 'Group, English Version, Global pop market target', descriptionKo: '그룹, 영어 버전, 글로벌 팝 시장 타겟' },
    { id: 82, category: 'Special', text: 'Female, Japanese Version, Anime opening style', descriptionKo: '여성, 일본어 버전, 애니메이션 오프닝 스타일' },
    { id: 83, category: 'Special', text: 'Male, Intro: Narrated Story, Cinematic universe', descriptionKo: '남성, 인트로: 내레이션 스토리, 세계관 설명' },
    { id: 84, category: 'Special', text: 'Female, Outro: Fading laughter, Tape rewind effect', descriptionKo: '여성, 아웃트로: 멀어지는 웃음소리, 테이프 되감기 효과' },
    { id: 85, category: 'Special', text: 'Group, Christmas Carol, Sleigh bells, Warm harmony', descriptionKo: '그룹, 크리스마스 캐롤, 썰매 방울, 따뜻한 화음' },
    { id: 86, category: 'Special', text: 'Male, Traditional Korean Instruments (Gukak) Mix, Fusion', descriptionKo: '남성, 국악기 믹스, 퓨전 사극 컨셉' },
    { id: 87, category: 'Special', text: 'Female, Halloween Concept, Spooky sound effects, Witch', descriptionKo: '여성, 할로윈 컨셉, 으스스한 효과음, 마녀' },
    { id: 88, category: 'Special', text: 'Group, Fan Chant Guide, "Hey! Ho!", Cheering', descriptionKo: '그룹, 응원법 가이드, "Hey! Ho!", 함성' },
    { id: 89, category: 'Special', text: 'Male, Unit Song (Rap Line), Hard hitting', descriptionKo: '남성, 유닛곡 (랩 라인), 강렬한 타격감' },
    { id: 90, category: 'Special', text: 'Female, Unit Song (Vocal Line), Acapella, Emotional', descriptionKo: '여성, 유닛곡 (보컬 라인), 아카펠라, 감성적인' },
    { id: 91, category: 'Special', text: 'Male, Cyberpunk 2077 vibe, Industrial, Future', descriptionKo: '남성, 사이버펑크 2077 느낌, 인더스트리얼, 미래' },
    { id: 92, category: 'Special', text: 'Female, Game Music Style, 8-bit sounds, Arcade', descriptionKo: '여성, 게임 음악 스타일, 8비트 사운드, 아케이드' },
    { id: 93, category: 'Special', text: 'Group, Concert Live Version, Band jam, Ad-libs', descriptionKo: '그룹, 콘서트 라이브 버전, 밴드 잼, 애드리브' },
    { id: 94, category: 'Special', text: 'Male, Remix, Sped up version, Nightcore', descriptionKo: '남성, 리믹스, 스피드 업 버전, 나이트코어' },
    { id: 95, category: 'Special', text: 'Female, Commercial Jingle, Short, Catchy, Brand', descriptionKo: '여성, CM송, 짧은, 중독성 있는, 브랜드' },
    { id: 96, category: 'Special', text: 'Male, Trot twist, Older audience, Fun', descriptionKo: '남성, 트로트가 가미된, 중장년층 타겟, 흥겨운' },
    { id: 97, category: 'Special', text: 'Female, Cheerleading, Drum line, High energy', descriptionKo: '여성, 치어리딩, 드럼 라인, 높은 에너지' },
    { id: 98, category: 'Special', text: 'Group, Anniversary Song, Thank you message, Touching', descriptionKo: '그룹, 데뷔 기념일 노래, 감사 메시지, 감동적인' },
    { id: 99, category: 'Special', text: 'Male, Producer Tag "JYP whisper", Signature sound', descriptionKo: '남성, 프로듀서 태그 (JYP 속삭임 등), 시그니처 사운드' },
    { id: 100, category: 'Special', text: 'Female, Ending Fairy, Heavy breathing, Final pose sound', descriptionKo: '여성, 엔딩 요정, 거친 숨소리, 마지막 포즈 사운드' },
  ];